# Generated by Django 4.1 on 2022-10-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="institute",
        ),
    ]
