# Generated by Django 4.1 on 2022-11-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_course_institute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsfiles",
            name="course",
            field=models.CharField(
                choices=[("BCA ", "BCA"), ("MCA", "MCA")], default="BCA", max_length=10
            ),
        ),
    ]
