# Generated by Django 4.1 on 2022-11-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_rsfiles_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rsfiles",
            name="migrated",
        ),
    ]
