# Generated by Django 4.1 on 2022-11-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_rsfiles_migrated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rsfiles",
            name="batch",
        ),
    ]
